# Generated by Django 3.2 on 2021-04-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
